#!/bin/sh

. git-sh-setup  # for die 
git status --porcelain | while IFS= read -r line;
do
        f=${line#???}
        case ${f} in
                *.less)
                        echo "Yess, compiling less into css."
                        lessc static/furora.less static/css/furora/furora.css
                        lessc static/jah/jah.less static/jah/css/jah.css
                        fb=${f%.less}
                        git add static/css/furora/furora.css
                        git add static/jah/css/jah.css
                        ;;
        esac
done

:
