#!/bin/sh

. git-sh-setup  # for die 
git status --porcelain | while IFS= read -r line;
do
        f=${line#???}
        case ${f} in
                *.less)
                        echo "Yess, compiling less into css."
                        lessc static/less/bootstrap.less static/css/bootstrap.css
                        lessc static/less/style.less static/css/style.css
                        lessc static/jah/less/bootstrap.less static/jah/css/bootstrap.css
                        fb=${f%.less}
                        git add static/css/bootstrap.css
                        git add static/jah/css/bootstrap.css
                        ;;
        esac
done

:
